
version: "3"

services:
    app:
        build:
            context: .
        volumes:
            - ./public:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - php
    php:
        image: php:fpm
        volumes:
            - ./public:/var/www/html
